<?xml version="1.0" ?>

<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <link name="base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.375"/>
            <geometry>
                <box size="2 1 0.75"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="100" />
            <inertia  ixx="0" ixy="0"  ixz="0"  iyy="0"  iyz="0"  izz="0" />
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.375"/>
            <geometry>
                <box size="2 1 0.75"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="base__base_link" type="prismatic">
        <parent link="base"/>
        <child link="base_link"/>
        <origin rpy="0 0 3.14" xyz="0.75 0 0.75"/>
        <axis xyz="1 0 0" />
        <limit effort="100.0" lower="0" upper="1.5" velocity="100" />
    </joint>
    
    <!-- <transmission name="trans_base__base_link">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base__base_link">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_base__base_link">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission> -->
    
    <link name="base_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.1"/>
            <geometry>
                <box size="0.25 0.25 0.2"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="5.0" />
            <inertia  ixx="0" ixy="0"  ixz="0"  iyy="0"  iyz="0"  izz="0" />
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.2"/>
            <geometry>
                <box size="0.25 0.25 0.2"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="base_link__link_1" type="revolute">
        <axis xyz="0 0 1" />
        <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5" />
        <origin rpy="0 0 1.5708" xyz="0 0 0.2"/>
        <parent link="base_link"/>
        <child link="link1"/>
    </joint>

    <transmission name="trans_base_link__link_1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_link__link_1">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_base_link__link_1">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>
    
    <link name="link1">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.15"/>
            <geometry>
                <cylinder radius="0.05" length="0.3"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="1.0" />
            <inertia  ixx="0" ixy="0"  ixz="0"  iyy="0"  iyz="0"  izz="0" />
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <geometry>
                <cylinder radius="0.05" length="0.3"/>
            </geometry>
        </collision>
    </link>

    <joint name="link_1__link_2" type="revolute">
        <axis xyz="0 1 0" />
        <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5" />
        <origin rpy="0 0 0" xyz="0 0 0.3"/>
        <parent link="link1"/>
        <child link="link2"/>
    </joint>

    <transmission name="trans_link_1__link_2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link_1__link_2">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_link_1__link_2">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <link name="link2">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.15"/>
            <geometry>
                <cylinder radius="0.05" length="0.3"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="1.0" />
            <inertia  ixx="0" ixy="0"  ixz="0"  iyy="0"  iyz="0"  izz="0" />
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <geometry>
                <cylinder radius="0.05" length="0.3"/>
            </geometry>
        </collision>
    </link>

    <joint name="link_2__link_3" type="revolute">
        <axis xyz="0 1 0" />
        <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5" />
        <origin rpy="0 0 0" xyz="0 0 0.3"/>
        <parent link="link2"/>
        <child link="link3"/>
    </joint>

    <transmission name="trans_link_2__link_3">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link_2__link_3">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_link_2__link_3">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <link name="link3">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.15"/>
            <geometry>
                <cylinder radius="0.05" length="0.3"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="1.0" />
            <inertia  ixx="0" ixy="0"  ixz="0"  iyy="0"  iyz="0"  izz="0" />
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <geometry>
                <cylinder radius="0.05" length="0.3"/>
            </geometry>
        </collision>
    </link>

    <joint name="link_3__link_4" type="revolute">
        <axis xyz="0 1 0" />
        <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5" />
        <origin rpy="0 0 0" xyz="0 0 0.3"/>
        <parent link="link3"/>
        <child link="link4"/>
    </joint>

    <transmission name="trans_link_3__link_4">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link_3__link_4">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_link_3__link_4">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <link name="link4">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.05"/>
            <geometry>
                <cylinder radius="0.05" length="0.1"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="1.0" />
            <inertia  ixx="0" ixy="0"  ixz="0"  iyy="0"  iyz="0"  izz="0" />
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.05"/>
            <geometry>
                <cylinder radius="0.05" length="0.1"/>
            </geometry>
        </collision>
    </link>

    <joint name="link_4__gripper_base" type="fixed">
        <origin rpy="0 0 1.5708" xyz="0 0 0.1"/>
        <parent link="link4"/>
        <child link="gripper_base"/>
    </joint>

    <link name="gripper_base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.025"/>
            <geometry>
                <box size="0.2 0.1 0.05"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="0.5" />
            <inertia  ixx="0" ixy="0"  ixz="0"  iyy="0"  iyz="0"  izz="0" />
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.025"/>
            <geometry>
                <box size="0.2 0.1 0.05"/>
            </geometry>
        </collision>
    </link>

    <!-- camera -->
    <!-- <joint name="camera_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0.05 0 ${height3 - axel_offset*2}" rpy="0 0 0"/>
        <parent link="link4"/>
        <child link="camera_link"/>
    </joint>

    <link name="camera_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        <material name="red"/>
        </visual>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link> -->

    <joint name="gripper_base__gripper_left" type="prismatic">
        <parent link="gripper_base"/>
        <child link="gripper_left"/>
        <origin rpy="0 0 3.14" xyz="0 0 0.05"/>
        <axis xyz="1 0 0" />
        <limit effort="100.0" lower=".075" upper="0.025" velocity="100" />
    </joint>
    
    <link name="gripper_left">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.05"/>
            <geometry>
                <box size="0.05 0.025 0.1"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="0.5" />
            <inertia  ixx="0" ixy="0"  ixz="0"  iyy="0"  iyz="0"  izz="0" />
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.05"/>
            <geometry>
                <box size="0.05 0.025 0.1"/>
            </geometry>
        </collision>
    </link>

    <joint name="gripper_base__gripper_right" type="prismatic">
        <parent link="gripper_base"/>
        <child link="gripper_right"/>
        <origin rpy="0 0 0" xyz="0 0 0.05"/>
        <axis xyz="1 0 0" />
        <limit effort="100.0" lower="0.025" upper="0.075" velocity="100" />
    </joint>
    
    <link name="gripper_right">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.05"/>
            <geometry>
                <box size="0.05 0.025 0.1"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="0.5" />
            <inertia  ixx="0" ixy="0"  ixz="0"  iyy="0"  iyz="0"  izz="0" />
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.05"/>
            <geometry>
                <box size="0.05 0.025 0.1"/>
            </geometry>
        </collision>
    </link>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        </plugin>
    </gazebo>
</robot>